/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type StoreSettings = {
  _id: string;
  _type: "storeSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: AccessibleImage;
  aboutImage?: AccessibleImage;
  visitImage?: AccessibleImage;
  contactImage?: AccessibleImage;
  sellImage?: AccessibleImage;
  visitNote?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: AccessibleImage;
  caption?: string;
  displayOrder: number;
  active?: boolean;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  type: "event" | "announcement";
  shortDescription: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: AccessibleImage;
  link?: {
    label: string;
    url: string;
  };
  date: string;
  endDate?: string;
  startTime?: string;
  endTime?: string;
  published?: boolean;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | StoreSettings
  | SanityImageAssetReference
  | AccessibleImage
  | GalleryItem
  | Event
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../lib/cms/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && published == true && defined(slug.current)] | order(date asc, _id asc) {  _id, _updatedAt, title, "slug": slug.current, type, shortDescription, date, endDate, startTime, endTime, featured}
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string;
  slug: string;
  type: "announcement" | "event";
  shortDescription: string;
  date: string;
  endDate: string | null;
  startTime: string | null;
  endTime: string | null;
  featured: boolean | null;
}>;

// Source: ../lib/cms/queries.ts
// Variable: EVENT_QUERY
// Query: *[_type == "event" && published == true && slug.current == $slug][0] {  _id, _updatedAt, title, "slug": slug.current, type, shortDescription, body, date, endDate, startTime, endTime, featured, image, link}
export type EVENT_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string;
  slug: string;
  type: "announcement" | "event";
  shortDescription: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  date: string;
  endDate: string | null;
  startTime: string | null;
  endTime: string | null;
  featured: boolean | null;
  image: AccessibleImage | null;
  link: {
    label: string;
    url: string;
  } | null;
} | null;

// Source: ../lib/cms/queries.ts
// Variable: GALLERY_QUERY
// Query: *[_type == "galleryItem" && active == true && defined(image.asset) && defined(image.alt)] | order(displayOrder asc, _id asc) {  _id, image, caption, displayOrder}
export type GALLERY_QUERY_RESULT = Array<{
  _id: string;
  image: AccessibleImage;
  caption: string | null;
  displayOrder: number;
}>;

// Source: ../lib/cms/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "storeSettings" && _id == "storeSettings"][0] {  heroImage, aboutImage, visitImage, contactImage, sellImage, visitNote}
export type SETTINGS_QUERY_RESULT = {
  heroImage: AccessibleImage | null;
  aboutImage: AccessibleImage | null;
  visitImage: AccessibleImage | null;
  contactImage: AccessibleImage | null;
  sellImage: AccessibleImage | null;
  visitNote: string | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "event" && published == true && defined(slug.current)] | order(date asc, _id asc) {\n  _id, _updatedAt, title, "slug": slug.current, type, shortDescription, date, endDate, startTime, endTime, featured\n}': EVENTS_QUERY_RESULT;
    '*[_type == "event" && published == true && slug.current == $slug][0] {\n  _id, _updatedAt, title, "slug": slug.current, type, shortDescription, body, date, endDate, startTime, endTime, featured, image, link\n}': EVENT_QUERY_RESULT;
    '*[_type == "galleryItem" && active == true && defined(image.asset) && defined(image.alt)] | order(displayOrder asc, _id asc) {\n  _id, image, caption, displayOrder\n}': GALLERY_QUERY_RESULT;
    '*[_type == "storeSettings" && _id == "storeSettings"][0] {\n  heroImage, aboutImage, visitImage, contactImage, sellImage, visitNote\n}': SETTINGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
